[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
second_program = "DqPzSxi1pZ2wogeYDDwyXx1WH77VyuxGGv9YnELpsgCd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
